# when using 3istsatus-rs with swaybar
# https://github.com/greshake/i3status-rust
#

theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "gpu {max}째"
chip = "amdgpu-pci-*"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "cpu {max}째"
chip = "k10temp-pci-*"

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "nvme: {max}째"
chip = "nvme-pci-*"

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "wifi: {max}째"
chip = "iwlwifi_1-*"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "6127:24585:Lite-On_Technology_Corp._ThinkPad_USB_Keyboard_with_TrackPoint"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
